### ISSUE TITLE
DetectorParameters is already defined in this compilation unit

### ISSUE THREAD

**Issue by giandifra** [quickbirdstudios/opencv-android#10]
Hi, 
I'm using opencv:3.4.4-contrib and i have a error when i use DetectorParameters.create()

```2019-05-13 11:46:02.891 13935-13935/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gianmarcodifrancesco.aruco, PID: 13935
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.aruco.DetectorParameters.create_0() (tried Java_org_opencv_aruco_DetectorParameters_create_10 and Java_org_opencv_aruco_DetectorParameters_create_10__)
        at org.opencv.aruco.DetectorParameters.create_0(Native Method)
        at org.opencv.aruco.DetectorParameters.create(DetectorParameters.java:29)
        at com.gianmarcodifrancesco.aruco.MainActivity.<init>(MainActivity.kt:119)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2869)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Can this error linked to "DetectorParameters is already defined in this compilation unit" problem ?

<img width="622" alt="Schermata 2019-05-13 alle 12 00 37" src="https://user-images.githubusercontent.com/44344581/57613297-cb5d7080-7576-11e9-9d03-488a7c1d6d55.png">

Thanks

**Comment by sellmair** [comment]
Have you initialized openCv properly? 
Example: 
```
if (!OpenCVLoader.initDebug())
   Log.e("OpenCv", "Unable to load OpenCV");
else
   Log.d("OpenCv", "OpenCV loaded");
```
