### ISSUE TITLE
No implementation found for long org.opencv.dnn.Dnn.readNetFromDarknet_0

### ISSUE THREAD

**Issue by zzxjl1** [quickbirdstudios/opencv-android#22]
`java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.dnn.Dnn.readNetFromDarknet_0(java.lang.String, java.lang.String) (tried Java_org_opencv_dnn_Dnn_readNetFromDarknet_10 and Java_org_opencv_dnn_Dnn_readNetFromDarknet_10__Ljava_lang_String_2Ljava_lang_String_2)
        at org.opencv.dnn.Dnn.readNetFromDarknet_0(Native Method)
        at org.opencv.dnn.Dnn.readNetFromDarknet(Dnn.java:321)
        at com.app.toomuchai.Tutorial1Activity.onCreate(Tutorial1Activity.java:91)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by sellmair** [comment]
Which version?
Are you loading the library with `OpenCVLoader.initDebug()`? 
Are you using the artifacts from jcenter or did you include our Gradle module directly?

**Comment by zzxjl1** [comment]
Which version? Are you using the artifacts from jcenter or did you include our Gradle module directly?
implementation 'com.quickbirdstudios:opencv:3.4.5'
Are you loading the library with OpenCVLoader.initDebug()?
Yes.

**Comment by zzxjl1** [comment]
Thanks for the quick response.

**Comment by zzxjl1** [comment]
Sorry, my bad putting`OpenCVLoader.initDebug()` in  `onResume()`, problem is solved after moving that line inside the `onCreate()` function. But there is still one problem. I tried to place my .weights inside assests folder and it seems doesn't support that.

**Comment by sellmair** [comment]
Will try to reproduce this
