### ISSUE TITLE
How can I use the forked repo in my own project?

### ISSUE THREAD

**Issue by Balasnest** [quickbirdstudios/opencv-android#40]
Need an help:
I have forked this repo and modify camera orientation. Also tried publish gradle using **jitpack** from forked one. But the problem is when I run the app, getting error saying `OpenCV error: Cannot load info library` for OpenCV when below code is executed.

```
public class MainActivity extends Activity {
    static {
        if (!OpenCVLoader.initDebug()) // Failed to load OpenCV
            Log.d("ERROR", "Unable to load OpenCV");
        else
            Log.d("SUCCESS", "OpenCV loaded");
    }
...
}
```
Error Logs:
```
D/OpenCV/StaticHelper: Trying to get library list
09-17 00:15:04.423 14150-14150/com.app E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
09-17 00:15:04.423 14150-14150/com.app D/OpenCV/StaticHelper: Library list: ""
09-17 00:15:04.423 14150-14150/com.app D/OpenCV/StaticHelper: First attempt to load libs
09-17 00:15:04.423 14150-14150/com.app D/OpenCV/StaticHelper: Trying to init OpenCV libs
09-17 00:15:04.423 14150-14150/com.app D/OpenCV/StaticHelper: Trying to load library opencv_java3
09-17 00:15:04.424 14150-14150/com.app D/OpenCV/StaticHelper: Cannot load library "opencv_java3"
09-17 00:15:04.424 14150-14150/com.app W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app-1/lib/arm, /data/app/com.app-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so"
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:67)
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:98)
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:42)
09-17 00:15:04.439 14150-14150/com.app W/System.err:     at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:107)
```
reference: [link](https://stackoverflow.com/questions/63926310/how-can-we-fork-opencv-android-repo-and-use-it-in-own-project)
why opencv lib not loading "libopencv_java3.so". Let me know how should I use the forked repo. Thanks!

**Comment by nasirky** [comment]
@Balasnest Sorry for taking some time to get back to you.

As far as I can tell, you are using 3.4 version of OpenCV. Can you try the latest one 4.3 and let us know if you are still facing the issue.

**Comment by nasirky** [comment]
@Balasnest I will now close this issue. Please open a new issue when you try out 4.3 and you still face the issue.

One solution that might work is to manually install ffmpeg on your system.
