### ISSUE TITLE
No implementation found for long org.opencv.face.LBPHFaceRecognizer.App crashes

### ISSUE THREAD

**Issue by AJV2018** [quickbirdstudios/opencv-android#55]
Crash log
 Process: com.attendanceapp, PID: 26207
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.face.LBPHFaceRecognizer.create_0(int, int, int, int, double) (tried Java_org_opencv_face_LBPHFaceRecognizer_create_10 and Java_org_opencv_face_LBPHFaceRecognizer_create_10__IIIID)
        at org.opencv.face.LBPHFaceRecognizer.create_0(Native Method)
        at org.opencv.face.LBPHFaceRecognizer.create(LBPHFaceRecognizer.java:91)
        at com.attendanceapp.recognizer.LBPHFRecognizer.<init>(LBPHFRecognizer.java:26)
        at com.reactlibrary.RNOpenCvLibraryModule.<init>(RNOpenCvLibraryModule.java:37)
        at com.reactlibrary.RNOpenCvLibraryPackage.createNativeModules(RNOpenCvLibraryPackage.java:15)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:923)

**Comment by AJV2018** [comment]
This crash happens only on arm64-v8a devices

**Comment by AJV2018** [comment]
I think the issue is from the opencv_java4.so file in arm64-v8a folder.


2021-07-03 12:14:11.832 24654-24654/? D/OpenCV/StaticHelper: Trying to get library list
2021-07-03 12:14:11.840 24654-24654/? E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2021-07-03 12:14:11.840 24654-24654/? D/OpenCV/StaticHelper: Library list: ""
2021-07-03 12:14:11.840 24654-24654/? D/OpenCV/StaticHelper: First attempt to load libs
2021-07-03 12:14:11.840 24654-24654/? D/OpenCV/StaticHelper: Trying to init OpenCV libs
2021-07-03 12:14:11.841 24654-24654/? D/OpenCV/StaticHelper: Trying to load library opencv_java4
2021-07-03 12:14:11.860 24654-24654/? D/OpenCV/StaticHelper: Cannot load library "opencv_java4"
2021-07-03 12:14:11.862 24654-24654/? W/System.err:     at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
2021-07-03 12:14:11.862 24654-24654/? W/System.err:     at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
2021-07-03 12:14:11.862 24654-24654/? W/System.err:     at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:107)
2021-07-03 12:14:11.864 24654-24654/? D/OpenCV/StaticHelper: First attempt to load libs fails
2021-07-03 12:14:11.864 24654-24654/? E/OpenCv: Unable to load OpenCV

**Comment by nasirky** [comment]
@AJV2018 That seems weird because this file these are built from the same source which means every architecture should work fine. Can you try changing the device? Can you also tell me which device are you using for testing?

**Comment by nasirky** [comment]
We have just released 4.5.3 via MavenCentral. Please go through the README file on how to integrate it. In case the issue still persists, please let us know.

**Comment by nasirky** [comment]
@AJV2018 I will close this issue now. If it still persists in the new releases, feel free to open a new issue.
